# Gestion des OpenAPI

spring:
  cloud:
    gateway:
      routes:
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: attrra
        url: /v3/api-docs/attrra
      - name: attrrc   
        url: /v3/api-docs/attrrc
      - name: find-nonlinked-rc-sudoc
        url: /v3/api-docs/find-nonlinked-rc-sudoc
      - name: find-ra-idref
        url: /v3/api-docs/find-ra-idref
      - name: linked-rc-idref-sudoc
        url: /v3/api-docs/linked-rc-idref-sudoc

---

# Set profil for LocalHost

spring:
  config:
    activate:
      on-profile: localhost

  sleuth:
    sampler:
      probability: 1.0

  # Configuration de Spring MVC pour la gestion des exceptions
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port : 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, metrics



logging:
  level:
    root: INFO
    fr:
      abes: DEBUG
    #reactor:
      #netty: debug
  config: classpath:log4j2-local.xml


---
# Set profil for Develop

spring:
  config:
    activate:
      on-profile: DEV

  # Configuration de Spring MVC pour la gestion des exceptions
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    fr:
      abes: DEBUG
  config: classpath:log4j2-dev.xml
