# Set profil for LocalHost

spring:
  config:
    activate:
      on-profile: localhost

  # Configuration de Spring MVC pour la gestion des exceptions
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port : 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, metrics

logging:
  level:
    root: INFO
    fr:
      abes: DEBUG

    org:
      springframework:
        r2dbc: DEBUG

  config: classpath:log4j2-local.xml

solr:
  base-url: ENC(PvGrFZ5FFPa+++bA+fZSEnTv8EhbR5dz1AEKiouKjFCuKPrQeoSPa/92y4UUgBuz8O2RqgF4x716OEHD5Xqf6J7cYHnbG0pg+0d2UQcXtgY=)

### Oracle
database:
  host: ENC(4ZMt2DUKAzRKfs972gaGSFRX6uZ9cKsgl9Jh5Y6BPVKEG/q1JHwlAH69u7ikBQmLlMC2GU9gmVkOZZFV3uPl+g==)
  port: 1521
  serviceName: ENC(02RMhlCIEQq4Fe4Xre8kmAZtqFGK0+ELNOV8CSFGiujBkAVzM1VOadaLBkv4+fRF)
  user: ENC(EHQ94F01KgeC4jqqOHY4if+2FIFdfTz23lEiJHz0V60YjuaRFHBqnXV3P8P6Ejaw)
  password: ENC(po9Kmx2mYRAgWEN8edcov+iTr/RLfFVd0s2sRORWvCTJ3Jm5u/glq/sf+HHcg0Ex)


---
# Set profil for Develop

spring:
  config:
    activate:
      on-profile: DEV

  # Configuration de Spring MVC pour la gestion des exceptions
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    fr:
      abes: DEBUG
  config: classpath:log4j2-dev.xml

solr:
  base-url: ENC(PvGrFZ5FFPa+++bA+fZSEnTv8EhbR5dz1AEKiouKjFCuKPrQeoSPa/92y4UUgBuz8O2RqgF4x716OEHD5Xqf6J7cYHnbG0pg+0d2UQcXtgY=)
  
### Oracle
database:
  host: ENC(4ZMt2DUKAzRKfs972gaGSFRX6uZ9cKsgl9Jh5Y6BPVKEG/q1JHwlAH69u7ikBQmLlMC2GU9gmVkOZZFV3uPl+g==)
  port: 1521
  serviceName: ENC(02RMhlCIEQq4Fe4Xre8kmAZtqFGK0+ELNOV8CSFGiujBkAVzM1VOadaLBkv4+fRF)
  user: ENC(EHQ94F01KgeC4jqqOHY4if+2FIFdfTz23lEiJHz0V60YjuaRFHBqnXV3P8P6Ejaw)
  password: ENC(po9Kmx2mYRAgWEN8edcov+iTr/RLfFVd0s2sRORWvCTJ3Jm5u/glq/sf+HHcg0Ex)
