# Set profil for LocalHost

spring:
  config:
    activate:
      on-profile: localhost

  sleuth:
    sampler:
      probability: 1.0

  # Configuration de Spring MVC pour la gestion des exceptions
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port : 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    root: INFO
    fr:
      abes: DEBUG
    #reactor:
      #netty: debug
  config: classpath:log4j2-local.xml

solr:
  base-url: ENC(PvGrFZ5FFPa+++bA+fZSEnTv8EhbR5dz1AEKiouKjFCuKPrQeoSPa/92y4UUgBuz8O2RqgF4x716OEHD5Xqf6J7cYHnbG0pg+0d2UQcXtgY=)

### Oracle
database:
  host: ENC(3pu+0M425dSDyKQNLWAMl+m2BeB5sPvkJNNrReM9QNSxXz36VaOHa+vd6PQdX7BiWemamruoXy/3i1jN99Qp/Q==)
  port: 1521
  serviceName: ENC(BeB1x+qYuTvAF7JuUizfsmFy8V3pv9YRP0rIoEdT5e/OJIQLVNPDBMgbk3EHWZRL)
  user: ENC(nAYUgT/brXtO5BjIl+Q2LnZVJqWGlNjeureJ1DURsDXeErYskqHhRInLWsCxVspl)
  password: ENC(IqfKUUapHp/9U/nBiaOq3b/BYs9k11g9EkgFUECP9nob1/JMjz0Kv2iXF2UiCKEM)



---
# Set profil for Develop

spring:
  config:
    activate:
      on-profile: DEV

  # Configuration de Spring MVC pour la gestion des exceptions
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    fr:
      abes: DEBUG
  config: classpath:log4j2-dev.xml

solr:
  base-url: ENC(PvGrFZ5FFPa+++bA+fZSEnTv8EhbR5dz1AEKiouKjFCuKPrQeoSPa/92y4UUgBuz8O2RqgF4x716OEHD5Xqf6J7cYHnbG0pg+0d2UQcXtgY=)
